name: FoolsGold
description: Make several humorus items availible via command
author: RypoFalem
version: 0.1
api-version: 1.13
main: io.github.rypofalem.foolsgold.FoolsGoldPlugin
depend: [ Custom, GenericEvents ]
commands:
  fgmerchant:
    description: Access FoolsGold merchant
    permission: foolsgold.merchant
permissions:
  foolsgold.merchant:
    description: use fgmerchant command